name: Deploy Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: REPO_NAME
          script: |
            if [ ! -d ~/projects/$REPO_NAME ]; then
              mkdir -p ~/projects
              git clone git@github.com:${{ github.repository }}.git ~/projects/$REPO_NAME
            fi
            cd ~/projects/$REPO_NAME

            mkdir -p ./data/main_db

            echo "GROUP_TOKEN=${{ secrets.GROUP_TOKEN }}" > .env.main
            echo "USER_TOKEN=${{ secrets.USER_TOKEN }}" >> .env.main
            echo "ALBUM_ID=${{ secrets.ALBUM_ID }}" >> .env.main
            echo "GROUP_ID=${{ secrets.GROUP_ID }}" >> .env.main
            echo "SUPER_ADMINS=${{ secrets.SUPER_ADMINS }}" >> .env.main
            echo "POSTGRES_DB=postgres" >> .env.main
            echo "POSTGRES_USER=postgres" >> .env.main
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env.main
            echo "POSTGRES_HOST=db" >> .env.main

            git pull origin main
            npm run docker:main:up
